name       : dleyna-server
version    : 0.5.0
release    : 1
source     :
    - https://01.org/sites/default/files/downloads/dleyna/dleyna-server-0.5.0.tar.gz : 65aea97df031ac2ceeae04bf8473d2a260db58ced737992f882fe331ec3f19ae
license    : LGPL-2.1
summary    : Library to discover, browse and manipulate Digital Media Servers
description: |
    Library to discover, browse and manipulate Digital Media Servers
builddeps  :
    - pkgconfig(dleyna-core-1.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gssdp-1.0)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
